// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AircraftStats = { aircraftType: string, totalHoursAll: number, totalFuelAll: number, totalFlightsAll: number, totalHoursCompleted: number, totalFuelCompleted: number, totalFlightsCompleted: number, lastAirport: string, };
