// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Config = { logDirectory: string | null, screenshotDirectories: Array<string>, screenshotRegexEnabled: boolean, screenshotRegex: string, autoUploadScreenshots: boolean, enableWebhook: boolean, serviceUrl: string, apiToken: string, openAtLogin: boolean, startMinimized: boolean, injectButterlogTraffic: boolean, autoShareFlights: boolean, };
