// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Config = { logDirectory: string | null, screenshotDirectories: Array<string>, screenshotRegexEnabled: boolean, screenshotRegex: string, autoUploadScreenshots: boolean, enableWebhook: boolean, serviceUrl: string, apiToken: string, openAtLogin: boolean, startMinimized: boolean, injectButterlogTraffic: boolean, autoShareFlights: boolean, 
/**
 * Stream the flight track to the service while airborne, so it can be
 * watched live on the web. Defaults to the auto-share setting on upgrade
 * so existing users get the behaviour they already expected.
 */
shareLiveFlights: boolean, 
/**
 * Let the pilot act on their own simulator from the live flight page.
 * Off by default and deliberately not derived from any other setting:
 * logging in should not hand anyone a lever on a running sim.
 */
allowRemoteCommands: boolean, 
/**
 * Also allow the beta autopilot controls. Separate from the switch above
 * because those drive the *default* autopilot and do nothing on add-on
 * aircraft that run their own.
 */
allowBetaCommands: boolean, };
