// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlightEvent } from "./FlightEvent";

export type FlightSummary = { filename: string, startIcao: string, startAirportName: string, endIcao: string, endAirportName: string, startTime: string, endTime: string, durationMinutes: number, fileSizeBytes: number, aircraftTitle: string, livery: string, resolvedIcao: string, resolvedAirline: string, atcModel: string, atcId: string, maxAltitude: number, maxGroundSpeed: number, fuelConsumed: number, events: Array<FlightEvent>, screenshotCount: number, notes: string, };
