// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlightEvent = { timestamp: string, eventType: string, latitude: number, longitude: number, touchdownFpm: number | null, landingG: number | null, offsetPercent: number | null, thresholdDistFt: number | null, vsVariance: number | null, iasVariance: number | null, approachStability: number | null, heading: number | null, };
