// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlightMetrics } from "./FlightMetrics";

export type FlightLogRow = { timestamp: string, metrics: FlightMetrics, };
