// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackedAircraftDebugInfo } from "./TrackedAircraftDebugInfo";

export type MultiplayerDebugInfo = { publicAddress: string | null, peers: Array<string>, trackedAircrafts: Array<TrackedAircraftDebugInfo>, };
