// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Screenshot = { id: number, flightId: string, aircraftTitle: string, path: string, timestamp: string, latitude: number, longitude: number, remoteHash: string | null, remoteUrl: string | null, };
