// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackedAircraftDebugInfo = { id: string, aircraft: string, atcModel: string, objectClass: string, category: string, numEngines: number, engineType: string, lastSeenSecondsAgo: number, latitude: number, longitude: number, gpsAltitudeMsl: number, indicatedAltitude: number, groundSpeed: number, heading: number, track: number, pitchAngle: number, rollAngle: number, };
