// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackedAircraftDebugInfo = { id: string,
/**
 * Username of the peer this aircraft belongs to (from the service); empty
 * if the peer's name isn't known.
 */
username: string, aircraft: string, atcModel: string,
/**
 * ICAO type designator the sender deduced from its title + livery (may be empty).
 */
resolvedIcao: string, 
/**
 * Operating airline name (derived locally from `resolved_airline_icao`; may be empty).
 */
resolvedAirline: string, 
/**
 * Portable ICAO designator of the operating airline from the wire (may be empty).
 */
resolvedAirlineIcao: string, 
/**
 * Raw sim livery string of the peer (may be empty).
 */
livery: string, 
/**
 * Local model chosen to render this peer; empty when the receiver defers selection.
 */
chosenModel: string, objectClass: string, category: string, numEngines: number, engineType: string, lastSeenSecondsAgo: number, latitude: number, longitude: number, gpsAltitudeMsl: number, indicatedAltitude: number, groundSpeed: number, heading: number, track: number, pitchAngle: number, rollAngle: number, };
